"""refactor_feeds

Revision ID: 05e54473203a
Revises: 2c4ebd357223
Create Date: 2026-01-04 21:43:45.932218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05e54473203a'
down_revision: Union[str, Sequence[str], None] = '2c4ebd357223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fishfeed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Rename table instead of drop/create to preserve data
    op.rename_table('pondfeed', 'pondfeedpurchase')
    
    # Add new column feed_id
    with op.batch_alter_table('pondfeedpurchase') as batch_op:
        batch_op.add_column(sa.Column('feed_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pondfeedpurchase_feed_id_fishfeed', 'fishfeed', ['feed_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pondfeed',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pond_id', sa.INTEGER(), nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit_id', sa.INTEGER(), nullable=False),
    sa.Column('price_per_unit', sa.FLOAT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pondfeedpurchase')
    op.drop_table('fishfeed')
    # ### end Alembic commands ###
