"""add_fishbuyertransaction

Revision ID: 2c4ebd357223
Revises: c5ae8e2e5f49
Create Date: 2026-01-04 21:10:14.826986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4ebd357223'
down_revision: Union[str, Sequence[str], None] = 'c5ae8e2e5f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
