"""Add debtor and debtor_transaction tables

Revision ID: 62c1a13c8cb6
Revises: b7a06ac0f660
Create Date: 2025-12-01 01:59:44.095777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c1a13c8cb6'
down_revision: Union[str, Sequence[str], None] = 'b7a06ac0f660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
