"""add_sale_type_to_fish_sale

Revision ID: 64c8187148d1
Revises: e2c84b1e7867
Create Date: 2025-12-01 22:50:48.219958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64c8187148d1'
down_revision: Union[str, Sequence[str], None] = 'e2c84b1e7867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishsale', sa.Column('sale_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='detailed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fishsale', 'sale_type')
    # ### end Alembic commands ###
