"""add_expense_and_expense_type_tables

Revision ID: 6c142176f62d
Revises: 62c1a13c8cb6
Create Date: 2025-12-01 03:24:40.497270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c142176f62d'
down_revision: Union[str, Sequence[str], None] = '62c1a13c8cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
