"""Add creditor_type and is_active fields

Revision ID: b7a06ac0f660
Revises: 2d4d62d12722
Create Date: 2025-11-30 11:26:55.089486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a06ac0f660'
down_revision: Union[str, Sequence[str], None] = '2d4d62d12722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creditor', sa.Column('creditor_type', sa.String(), nullable=True))
    op.add_column('creditor', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creditor', 'is_active')
    op.drop_column('creditor', 'creditor_type')
    # ### end Alembic commands ###
