"""Add FishBuyer and update FishSale

Revision ID: c5ae8e2e5f49
Revises: 4ba6c6d8b6ef
Create Date: 2026-01-04 20:47:10.578417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ae8e2e5f49'
down_revision: Union[str, Sequence[str], None] = '4ba6c6d8b6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import sqlmodel

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('fishbuyer',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    
    with op.batch_alter_table('fishsale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="paid"))
        batch_op.add_column(sa.Column('paid_amount', sa.Float(), nullable=False, server_default="0.0"))
        batch_op.add_column(sa.Column('due_amount', sa.Float(), nullable=False, server_default="0.0"))
        batch_op.create_foreign_key('fk_fishsale_buyer', 'fishbuyer', ['buyer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishsale', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fishsale_buyer', type_='foreignkey')
        batch_op.drop_column('due_amount')
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('buyer_id')

    op.drop_table('fishbuyer')
    # ### end Alembic commands ###
